function synapse = getSynapse(type)
    baseParams = struct('plotflag', true, 'plot_histograms', false, ...
        'num_channels', 72, 'num_release_sites', 16, ...
        'distance_vesicle_membrane', 5, 'intervesicle_distance', 100, 'vesicle_radius', 20);

    immature_tightness_array = linspace(2, 3.5, 5);


    switch type
        case 'r'
            params = struct( ...
                'channel_distribution_method', 'regular_band_n', ...
                'channel_distribution_parameters', struct(...
                    'length', 24*30, ...
                    'wpos', [-40, 0, 40] ...
                ) ...
            );
        case 'm'
            tightness = 1;
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        case 'i1'
            tightness = immature_tightness_array(1);
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        case 'i2'
            tightness = immature_tightness_array(2);
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        case 'i3'
            tightness = immature_tightness_array(3);
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        case 'i4'
            tightness = immature_tightness_array(4);
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        case 'i5'
            tightness = immature_tightness_array(5);
            params = struct( ...
                'channel_distribution_method', 'tightness', ...
                'channel_distribution_parameters', struct( ...
                    "tightness", tightness, ...
                    "x_rad", 300, "y_rad", 200 ...
                ) ...
            );
        otherwise
            disp(type)
            error('Unknown synapse configuration');
    end

    combineStructs = @(x,y) cell2struct([struct2cell(x);struct2cell(y)],[fieldnames(x);fieldnames(y)]);
    combinedParams = combineStructs(baseParams, params);
    cnames = combinedParamsToNameValuePairs(combinedParams);

    synapse = RibbonSynapse_v5(cnames{:});

end

function nameValuePairs = combinedParamsToNameValuePairs(params)
    fields = fieldnames(params);
    nameValuePairs = cell(1, 2*numel(fields));
    for i = 1:numel(fields)
        nameValuePairs{2*i-1} = fields{i};
        nameValuePairs{2*i} = params.(fields{i});
    end
end